### ISSUE TITLE
Vehicle Bar Bugs

### ISSUE THREAD

**Issue by Toxicom** [Toxicom/toxiui#98]
### Checklist
- [x] ~~Shadows are still present with ElvUI Theme Shadows disabled~~
- [ ] Moving an ability on Vehicle Bar should not make some buttons disappear
- [ ] Perfromance issues, microstutters
- [x] ~~Vigor Bar doesn't work for Evoker's [Soar](https://www.wowhead.com/spell=381322/soar)~~

**Comment by Toxicom** [comment]
Shadows fix: c184730050b532e428abce85efa189990ecaa8c4

**Comment by Bonesomething** [comment]
On my Envoker, the vigor bars doesn't show up correctly when using Soar.  Works fine on dragon riding mounts.  Using ElvUI: 13.66 + WindTools 3.58 + ToxiUI v6.6.8-beta.8
![ToxiUI Soar vigor bug](https://github.com/Toxicom/toxiui/assets/173422418/03690671-73e1-4927-aa41-79e8fdc1bb23)

**Comment by Toxicom** [comment]
> On my Envoker, the vigor bars doesn't show up correctly when using Soar. Works fine on dragon riding mounts. Using ElvUI: 13.66 + WindTools 3.58 + ToxiUI v6.6.8-beta.8 ![ToxiUI Soar vigor bug](https://private-user-images.githubusercontent.com/173422418/341603422-03690671-73e1-4927-aa41-79e8fdc1bb23.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTA3ODEsIm5iZiI6MTcxODk1MDQ4MSwicGF0aCI6Ii8xNzM0MjI0MTgvMzQxNjAzNDIyLTAzNjkwNjcxLTczZTEtNDkyNy1hYTQxLTc5ZThmZGMxYmIyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNjE0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2Q4MjE5MWFhMGI0ZThhN2U4NjBiYTVkMDMxYjEyZDI3ZDYzZjhlMjAyMmFlOGMwZGY0NmE5MGQ1NWIxZGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Nkj6Ec_SdliAEAfyYkRLFtJAhuBJ7DQGDShPqs20DnU)

Should be fixed in the next beta build

**Comment by Bonesomething** [comment]
I just tried v6.6.8-beta 9 and still isn't working for me.  In the screenshot it will show the default blizzard vigor UI, but I also got that sometimes with beta 8.
![Envoker ToxiUI vigor bug 2](https://github.com/Toxicom/toxiui/assets/173422418/06cf994a-e643-4357-a6b0-f9f6f3e3d7df)

**Comment by Toxicom** [comment]
Its not released yet :) will probably release it tomorrow evening, or sunday. Im out most of the weekend

**Comment by Toxicom** [comment]
Hey @Bonesomething, I've just released `v6.6.8-beta.10` which should address and fix your issue.

https://github.com/Toxicom/toxiui/releases/tag/v6.6.8-beta.10 or get it on CurseForge/Wago
